# nick fragale Theme/Blog - Jekyll Theme
# the glas theme: https://github.com/SpaceG/glas
# Author: Nick Fragale
# Theme: glas
# Source: https://github.com/shoemakerlevy9.github.io
# Mail: nicholas.fragale@gmail.com
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Nick Fragale
#What is the name of the events or talks you would like to host? (Example Brownbags, Talks, Lighting Talks)
event_label: Events

description: > # "
  Nick Fragale is a Robtics Engineer fron the Twin Cities

baseurl: "" # the subpath of your site, e.g. /blog
url: "www.nickfragale.com" # the base hostname & protocol for your site

#These settings might be able to go?
author: Nick Fragale
twitter_username: nicholasfragale
github_username:  shoemakerlevy9

# Navigation (2nd level links supported)
nav:
  Home:           
    - '/'
  Adventures:           
    - '/adventures/'
    - { Categories: '/adventures/categories/' }
    - { Tags: '/adventures/tags/' }
  Projects:
    - '/projects/'
    - { Categories: '/projects/categories/' }
    - { Tags: '/projects/tags/' }
  About:          
    - '/about/'



# Build settings
markdown: kramdown

#Have to show future posts for future events.
future: true

permalink: /event/:title.html
